services:
  # ==========================================
  # WhatsApp MCP Service (All-in-One)
  # Runs Python Agent SDK + WhatsApp MCP in Docker
  # ==========================================
  - type: web
    name: whatsapp-mcp
    runtime: docker
    plan: starter  # $7/month - use 'free' for free tier (spins down after 15 min)
    region: oregon # or 'frankfurt', 'singapore'

    # Docker configuration
    dockerfilePath: ./Dockerfile.render
    dockerContext: .

    # Health check endpoint
    healthCheckPath: /health

    # Environment variables
    # NOTE: Set these in Render dashboard (don't commit secrets!)
    envVars:
      # Claude API
      - key: ANTHROPIC_API_KEY
        sync: false  # Set manually in dashboard (REQUIRED)

      # WhatsApp Business API
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false  # Set manually (REQUIRED)

      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false  # Set manually (REQUIRED)

      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false  # Set manually (REQUIRED)

      # Service configuration
      - key: PORT
        value: 8000  # Default port (Render may override)

    # Auto-deploy when pushing to main branch
    autoDeploy: true

# ==========================================
# DEPLOYMENT INSTRUCTIONS:
# ==========================================
#
# This configuration deploys ONE service to Render that contains:
# 1. Python Claude Agent SDK Manager (FastAPI)
# 2. WhatsApp MCP server (exposes WhatsApp tools)
# 3. Agent spawning and management
#
# ARCHITECTURE (per your diagram):
# - WhatsApp User sends message
# - Webhook POST -> Render FastAPI service
# - Python Claude Agent SDK Manager spawns agents
# - Agents use MCP tools (WhatsApp MCP)
# - Response sent back via WhatsApp API
#
# SETUP STEPS:
# 1. Push this repo to GitHub
# 2. Go to render.com and sign up/login
# 3. Click "New" -> "Web Service"
# 4. Connect your GitHub repo
# 5. Render will use this render.yaml Blueprint
# 6. Set environment variables in Render dashboard
# 7. Deploy!
#
# YOUR SERVICE URL:
# https://whatsapp-mcp-t9mi.onrender.com
#
# CONFIGURE WHATSAPP:
# 1. Go to Meta Business Suite -> WhatsApp -> Configuration
# 2. Set webhook URL: https://whatsapp-mcp-t9mi.onrender.com/webhook
# 3. Set verify token: (same as WHATSAPP_WEBHOOK_VERIFY_TOKEN)
# 4. Subscribe to 'messages' events
# 5. Test by sending a message to your WhatsApp Business number
#
# ==========================================
